### ISSUE TITLE
Infinite appointment with incorrect dates

### ISSUE THREAD

**Issue by eliottdbs** [muzhaqi16/eCalendar#5]
**Issue**: An appointment ca be everywhere (on every date possible)

**Reproducing**: The end date must be before the start date

![image](https://user-images.githubusercontent.com/56924502/107512923-c4c6b780-6ba7-11eb-8b96-9e5d75eb2fb0.png)
NB: The update panel shows the specified dates on the front, and we can see the appointment everywhere in the back.

**Comment by muzhaqi16** [comment]
Thank you @eliottdbs for pointing out this issue. I can confirm that it has been fixed with the latest MR #6
